name: weather_forecast
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_launcher_icons: ^0.8.1
  image_picker: ^0.6.7+12
  weather_icons: ^2.0.2
  flutter_svg: ^0.19.0
  intl: ^0.16.1
  http: ^0.12.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "image/weather_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/